### PR TITLE
Add _FILE environment variables.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

First, I want to thank you for providing this docker image.

In this PR, I added two new envrionment variables:

1. `DOLI_DB_PASSWORD_FILE`
1. `DOLI_ADMIN_PASSWORD_FILE`

These variables can be used to give a file which store the database/admin password.
This is needed to use `docker secret`, thus to avoid having clear passwords in a `docker-compose.yml`.
The modifications do not modify the default values for these variables.

If both the conventionnal and _FILE variables are given an error is thrown:
```bash
me@home$ docker run --rm -ti -e DOLI_DB_PASSWORD=foo -e DOLI_DB_PASSWORD_FILE=/bar tuxgasy/dolibarr
Both DOLI_DB_PASSWORD and DOLI_DB_PASSWORD_FILE are set (but are exclusive)
```
The added code was taken from [MariaDB entrypoint](https://github.com/docker-library/mariadb/blob/master/docker-entrypoint.sh#L25).

Best regards.

### CODE REVIEW

**Comment by tuxgasy** [comment]
@mathieupotier  what do you think of this PR?
This allows to use docker secret without breaking compatibility.

**Review by mathieupotier — APPROVED** [review]
I made this kind of change here : https://github.com/tuxgasy/docker-dolibarr/pull/44

I would like to consider also the username as secret also @eiffel-fl.

Looks good to me except 2 non blocking suggests :
1. add username as secret file valued also.
2. add some documentation, but my PR could deal with it if this one is merged.

Sounds good to me @tuxgasy (sorry for the lag, but I had a hard week ^_^)

**Comment by tuxgasy** [comment]
Your implementations are almost identical. I will checking PR #44 which is more complete.

**Comment by eiffel-fl** [comment]
Hi.


I did not check the other PR before submitting this one.
Indeed, @mathieupotier's implementation in #44 is more complete, so I will opt for this one to be merged instead of mine.


Best regards.

**Pull request closed without merging**
