### PR TITLE
Fix dolibarr_main_instance_unique_id

### PR DESCRIPTION
**Pull request by AlbanDurrheimer**
Sorry, in my last pull request, I forgot to modify the code after my tests...

### CODE REVIEW

**Comment by BadPixxel** [comment]
Hi Alban,

I'm using this images on Gitlab CI, and now I have this error, maybe linked to your changes.


```
/usr/local/bin/docker-run.sh: line 261: warning: here-document at line 73 delimited by end-of-file (wanted `$dolibarr_main_instance_unique_id='${DOLI_INSTANCE_UNIQUE_ID}';')
/usr/local/bin/docker-run.sh: line 262: syntax error: unexpected end of file
```

BR

**Comment by AlbanDurrheimer** [comment]
Hi @BadPixxel,  
Yes, sorry, it's related to my latest changes. This pull request contains the correction.  
Until this pull request is merged, you can fix the problem by temporarily using my GIT repertory:  

- In docker compose:
```diff
services:
  dolibarr:
-   image: tuxgasy/dolibarr:{VERSION}
+   build: https://github.com/AlbanDurrheimer/docker-dolibarr.git#master:images/{DIRECTORY-VERSION}
```

{VERSION}: your Dolibarr version (if you use `latest`, it's `18`)
{DIRECTORY-VERSION}: this is the directory that matches your Dolibarr version (for Dolibarr `18`, it is `18.0.1-php8.1`) => https://github.com/AlbanDurrheimer/docker-dolibarr/tree/master/images  

Best regards

**Comment by BadPixxel** [comment]
Hi,

Thx but we cannot build images on CI/CD, I'll wait for dockerhub updates and let you knwo if this works! 

Thanks for your support!
Best regards

**Comment by BadPixxel** [comment]
Hi,

Many thanks, it worked! 
But now you have disabled old releases 11-14 by #131 and same problem persisted. 

Would it be possible to rever or rebuild those images? 

BR

**Comment by tuxgasy** [comment]
I rebuilt these images. It will be the last update of these versions.

**Pull request merged**
