### PR TITLE
run cron on background

### PR DESCRIPTION
**Pull request by ghost**
This PR changes the current CRON working mode.

Currently when cron is enabled (DOLI_CRON:1), the apache server does not start and two separate services are required to run the “CRON” and the “dolibarr” apache server.

When this PR is merged, the “CRON” will be launched in the background. A new variable (DOLI_CRON_SCHEDULE: */5 * * * * *) has been added to allow the launch frequency to be changed. By default, cron is run every minute.

### CODE REVIEW

**Comment by benvia** [comment]
This requires modifying all docker-compose files already deployed to prevent 2 Apache servers from running on for the same Dolibarr (including 2 running cron job at the same time).

From my point of view this is a breaking change.

This also break the concept of Docker, 1 container = 1 service

**Comment by tuxgasy** [comment]
As @benvia said, 1 container = 1 service.

**Comment by ghost** [comment]
You’re wrong. This is not a "service" but an inherent task element of the operation of dolibarr.

This is more consistent than disabling apache when cron is active and deploying the same container twice just to run a cron.

**Comment by benvia** [comment]
I take this from another discution about cron job for PHP app :

> Most docker instances nowadays have a separated "cron" container that offloads the cron jobs since some of those are quite intensive and can block the PHP procces for long time.

**Pull request closed without merging**
