### PR TITLE
Add env var to change php.ini upload size

### PR DESCRIPTION
**Pull request by vincowl**
Add an env var to allow change of   upload_max_filesize and post_max_size vars in php config

### CODE REVIEW

**Comment by tuxgasy** [comment]
Thanks for your PR.

- create 2 separate env vars for this
- use the following format for env var name : PHP_INI_<PHP_VAR_NAME> (eg: PHP_INI_UPLOAD_MAX_FILESIZE)
- update the README with new env vars

**Comment by vincowl** [comment]
@tuxgasy Sorry for the delay. Here are the requested changes.

**Review by tuxgasy — COMMENTED** [review]
Do not edit README.md directly because it will be overriten on every new Dolibarr version.

Edit README.template and then run update.sh script.

**Comment by vincowl** [comment]
@tuxgasy Should be ok like this

**Comment by tuxgasy** [comment]
You have to run update.sh script.

**Pull request merged**
