### PR TITLE
Add customs scripts via volume mount

### PR DESCRIPTION
**Pull request by Vaadasch**
Hi,

As i need to configure some things after the deployment of this image, i suggest to add this functionality.

By adding mount volume inside the container at : 
- /var/www/scripts/docker-init.d/php
- /var/www/scripts/docker-init.d/sql

We can use these folder to store scripts and sql files to be executed at the end of the deployment, at the end of the function "initializeDatabase" inside docker-run.sh, the same way as docker-init.php

I don't know what would be the best to the names of folders or other things, but the functionality will allow to automate and set up template on new deployments.

And will allow me to customize without creating lot of PR :wink:

### CODE REVIEW

**Review by tuxgasy — CHANGES_REQUESTED** [review]
> 
>     * /var/www/scripts/docker-init.d/php
> 

Just allow scripts in **/var/www/scripts/docker-init.d/**. Depending on the file extension, run the script with PHP or shell or import the SQL file.

>     * /var/www/scripts/docker-init.d/sql
> 
> 
> We can use these folder to store scripts and sql files to be executed at the end of the deployment, at the end of the function "initializeDatabase" inside docker-run.sh, the same way as docker-init.php

Mariadb docker image already allows the database to be initialized via the volume mount **/docker-entrypoint-initdb.d**.
If need, you can update the database via your custom script.

**Comment by Vaadasch** [comment]
>Just allow scripts in /var/www/scripts/docker-init.d/. Depending on the file extension, run the script with PHP or shell or import the SQL file.
Yep, that would be better indeed. For those who want to categorize inside folders, shell scripts will allow it.


> Mariadb docker image already allows the database to be initialized via the volume mount /docker-entrypoint-initdb.d. 
>If need, you can update the database via your custom script.
Will that not be erased by the importing of install/mysql/data/*.sql ?

**Comment by tuxgasy** [comment]
> Will that not be erased by the importing of install/mysql/data/*.sql ?

No but if the database is already initialized with Dolibarr data, the initializeDatabase function will not be called.

**Comment by Vaadasch** [comment]
Ok.
Thanks you for clarifying, it is indeed only to execution at the first initialisation of a new Dolibarr instance.
The rest should be done through the Dolibarr modules.

**Review by tuxgasy — APPROVED** [review]
I will test later.

**Pull request merged**
