### PR TITLE
Add "libreoffice-writer" to the Dockerfile.template file

### PR DESCRIPTION
**Pull request by rizerev**
With the `MAIN_ODT_AS_PDF` PDF option Dolibarr is able to automatically convert .odt files to .pdf files. For this feature to work libreoffice-writer has to be installed in the container.

Please pull.

### CODE REVIEW

**Comment by mathieupotier** [comment]
hi @rizerev,

I'll test this today, keeping you in touch @tuxgasy about the result of my non regression tests.

**Comment by mathieupotier** [comment]
Hi @rizerev,
As specified in the documentaion, those features are experimental ... https://wiki.dolibarr.org/index.php?title=Setup_Other

I suggest to add this package only on develop tag ... what do you think ?

**Comment by mathieupotier** [comment]
suggested change in your PR : https://github.com/rizerev/docker-dolibarr/pull/1

**Comment by rizerev** [comment]
Hi @mathieupotier!
Thank you for reviewing.

You are of course correct, this feature is experimental.
However, adding libreoffice to the container does not enable the feature. The idea behind adding this to all tags is that if one decides that they would like to enable this experimental feature they can do so without the additional hassle of having to modify their container or having to migrate to develop. Therefore I think it would make sense to keep the change for all tags, do you agree?

**Comment by mathieupotier** [comment]
Hi @rizerev,

Let's @tuxgasy decide on this, it's him which is maintaining the repo ... ^_^

For me, we have to be cautious about the size of images for production, so that's the point.

Regards

**Comment by rizerev** [comment]
Hi @mathieupotier!

Yes, good idea. I'm fine with both options. :+1: 
Maybe a third option would be to add -experimental tags where dependencies, such as libreoffice, for experimental features are installed. For example `13-experimental`.

I see your point about the size.
For me this is just a matter of time as to when the feature will be in a non-experimental state and libreoffice is needed in order for the container to fully support Dolibarr.

**Comment by tuxgasy** [comment]
Hi

I don't have a problem adding new features (even if it's experimental). But as @mathieupotier said, we must pay attention to the size of images.
Currently, size of image is already ~800MB. By adding just libreoffice-writer, the size is 1.16GB...

There are already many tags, I don't want to add even more (I think we must stop php5 support and add support for php8).

You can create your own Dockerfile using this image and add this feature. It's very easy to integrate it with docker-compose (or any other tool). I do like this for some of my projects.

**Pull request closed without merging**
